version: "3.3"

services:
  database:
    container_name: django-sie
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=sie
      - POSTGRES_USER=sie
    ports:
      - 5432:5432