# Generated by Django 3.0.8 on 2020-07-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200710_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name',), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('client', 'name'), 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
    ]
