# Generated by Django 3.0.8 on 2020-07-10 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_auto_20200710_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('status', models.CharField(default='open', max_length=10)),
                ('validate', models.DateField()),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unity_price', models.DecimalField(decimal_places=10, max_digits=16)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimates.Estimate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
