# Generated by Django 3.0.8 on 2020-07-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimate',
            options={'ordering': ('client', 'validate', 'status'), 'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.AlterModelOptions(
            name='estimateitem',
            options={'ordering': ('name', 'description'), 'verbose_name': 'Item do orçamento', 'verbose_name_plural': 'Itens do orçamento'},
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='unity_price',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
