# Generated by Django 3.0.8 on 2020-07-10 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200710_0325'),
        ('estimates', '0002_auto_20200710_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
    ]
